version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    redis:
        restart: always
        image: redis:latest
        expose:
            - "6379"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - static_volume:/code/static
        env_file:
          ./backend/.env
        command: gunicorn --workers=3 --bind 0.0.0.0:8000 conf.wsgi
        depends_on:
            - db
            - redis

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
          - static_volume:/usr/share/nginx/static
        ports:
            - "80:80"
        depends_on:
            - backend

volumes:
  static_volume:
