version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    redis:
        restart: always
        image: redis:latest
        expose:
            - "6379"
    
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes: 
            - ./backend:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - frontend

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - "4200:4200"
        volumes:
            - /opt/app/node_modules
            - ./frontend:/opt/app
